version: 2
updates:
  - directory: /
    package-ecosystem: gitsubmodule
    allow:
      - dependency-name: vscode
    open-pull-requests-limit: 1
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: npm
    ignore:
      - dependency-name: "jsonc-parser"
      - dependency-name: semver
      - dependency-name: typescript
      - dependency-name: "@types/*"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
