version: 2
updates:
  - directory: /
    package-ecosystem: gitsubmodule
    allow:
      - dependency-name: vscode
    open-pull-requests-limit: 1
    schedule:
      interval: weekly

  - directory: /packages/service
    package-ecosystem: npm
    ignore:
      - dependency-name: "jsonc-parser"
      - dependency-name: semver
      - dependency-name: typescript
      - dependency-name: "@types/semver"
    open-pull-requests-limit: 5
    schedule:
      interval: weekly

  - directory: /packages/server
    package-ecosystem: npm
    ignore:
      - dependency-name: "@vtsls/typescript-lanuguage-service"
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: npm
    ignore:
      - dependency-name: "@types/node"
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
