name: Update lock file

on:
  push:
    branches:
      - "release-please-**"

jobs:
  update-pr:
    permissions:
      contents: write
    name: update-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - run: pnpm install --lockfile-only
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lock file
          file_pattern: pnpm-lock.yaml
          commit_options: "--no-verify --signoff"
          commit_user_name: release-please[bot]
          commit_user_email: 55107282+release-please[bot]@users.noreply.github.com
          skip_dirty_check: true
